from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_product = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_product.setGeometry(QtCore.QRect(20, 20, 60, 20))
        self.label_product.setObjectName("label_product")
        self.productDropdown = QtWidgets.QComboBox(parent=self.centralwidget)
        self.productDropdown.setGeometry(QtCore.QRect(100, 20, 200, 25))
        self.productDropdown.setObjectName("productDropdown")
        self.label_quantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_quantity.setGeometry(QtCore.QRect(20, 60, 60, 20))
        self.label_quantity.setObjectName("label_quantity")
        self.quantityInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.quantityInput.setGeometry(QtCore.QRect(100, 60, 200, 25))
        self.quantityInput.setObjectName("quantityInput")
        self.label_discount = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_discount.setGeometry(QtCore.QRect(20, 100, 60, 20))
        self.label_discount.setObjectName("label_discount")
        self.discountDropdown = QtWidgets.QComboBox(parent=self.centralwidget)
        self.discountDropdown.setGeometry(QtCore.QRect(100, 100, 100, 25))
        self.discountDropdown.setObjectName("discountDropdown")
        self.addToCartButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addToCartButton.setGeometry(QtCore.QRect(20, 140, 100, 30))
        self.addToCartButton.setObjectName("addToCartButton")
        self.clearButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(140, 140, 100, 30))
        self.clearButton.setObjectName("clearButton")
        self.cartDisplay = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.cartDisplay.setGeometry(QtCore.QRect(20, 180, 350, 70))
        self.cartDisplay.setObjectName("cartDisplay")
        self.totalLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.totalLabel.setGeometry(QtCore.QRect(20, 260, 200, 20))
        self.totalLabel.setObjectName("totalLabel")
        self.label_product_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_product_2.setGeometry(QtCore.QRect(280, 100, 101, 20))
        self.label_product_2.setObjectName("label_product_2")
        self.label_product_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_product_3.setGeometry(QtCore.QRect(280, 120, 101, 20))
        self.label_product_3.setObjectName("label_product_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POS Application"))
        self.label_product.setText(_translate("MainWindow", "Product"))
        self.label_quantity.setText(_translate("MainWindow", "Quantity"))
        self.label_discount.setText(_translate("MainWindow", "Discount"))
        self.addToCartButton.setText(_translate("MainWindow", "Add to Cart"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.totalLabel.setText(_translate("MainWindow", "Total: Rp. 0"))
        self.label_product_2.setText(_translate("MainWindow", "Hendra Ahmad Yani"))
        self.label_product_3.setText(_translate("MainWindow", "F1D022122"))
